# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OrderSpeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OrderSpeed
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
  
  pod 'Alamofire', '~> 5.0'
  pod 'SwiftyJSON'
  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
end
